services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:alpine

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - pdf_data:/shared_pdf
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/appdb
      - PDF_DIRECTORY=/shared_pdf
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: celery -A app.celery_utils.celery_app worker --loglevel=info
    volumes:
      - pdf_data:/shared_pdf
    environment:
      - PDF_DIRECTORY=/shared_pdf
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/appdb
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  pdf_data: